@extends('layouts.main')
@section('title') SeedUP — виробництво @endsection
@section('description', 'Як SeedUP вирощує насіння соняшнику та кукурудзи: від добору генетики до очищення, калібрування і лабораторного контролю насіння.')
@section('canonical', route('about.production'))
@section('main-class', 'public-main')
@section('content-class', 'container-fluid p-0')
@section('content')
<section class="inner-hero inner-hero--dark"><div class="site-shell inner-hero__grid"><div><span class="section-kicker section-kicker--light">Виробництво в Україні</span><h1>Від генетики до готової <em>партії насіння</em></h1><p>Контрольований цикл вирощування, очищення, калібрування та перевірки якості.</p></div><div class="inner-hero__icon"><i class="fa-solid fa-industry"></i></div></div></section>
<section class="content-section"><div class="site-shell"><div class="section-heading section-heading--split"><div><span class="section-kicker">Технологія</span><h2>Шість етапів якості</h2></div><p>На кожному етапі фіксуємо ключові показники та відсіюємо матеріал, що не відповідає нашим вимогам.</p></div><ol class="process-grid"><li><span>01</span><i class="fa-solid fa-dna"></i><h3>Добір ліній</h3><p>Французькі батьківські форми з перевіреною чистотою.</p></li><li><span>02</span><i class="fa-solid fa-map-location-dot"></i><h3>Ізоляція ділянок</h3><p>Просторове розміщення та схема чергування батьківських рядків.</p></li><li><span>03</span><i class="fa-solid fa-seedling"></i><h3>Польовий контроль</h3><p>Живлення, захист рослин, контроль запилення та сортові прополки.</p></li><li><span>04</span><i class="fa-solid fa-tractor"></i><h3>Делікатне збирання</h3><p>Визначення оптимальної вологості та мінімізація пошкоджень.</p></li><li><span>05</span><i class="fa-solid fa-gears"></i><h3>Очищення</h3><p>Сушіння за щадного режиму, калібрування та видалення домішок.</p></li><li><span>06</span><i class="fa-solid fa-microscope"></i><h3>Лабораторія</h3><p>Фінальна перевірка схожості, енергії, вологості та чистоти.</p></li></ol></div></section>
<section class="content-section content-section--soft"><div class="site-shell split-feature"><div><span class="section-kicker">Повний контроль</span><h2>Насіння з передбачуваною поведінкою в полі</h2><p>Контроль технології допомагає зберегти генетичний потенціал і забезпечити рівномірні сходи.</p></div><ul class="check-list"><li><i class="fa-solid fa-check"></i>Генетична чистота</li><li><i class="fa-solid fa-check"></i>Висока енергія проростання</li><li><i class="fa-solid fa-check"></i>Точне калібрування</li><li><i class="fa-solid fa-check"></i>Захист від хвороб і шкідників</li></ul></div></section>
@include('blocks.contact-cta')
@endsection
