@extends('layouts.main')
@section('title') SeedUP — наука та агрономія @endsection
@section('description', 'Науковий підхід SeedUP до вирощування гібридів соняшнику та кукурудзи: генетика, ізоляція, живлення, захист і контроль якості.')
@section('canonical', route('about.science'))
@section('main-class', 'public-main')
@section('content-class', 'container-fluid p-0')
@section('content')
<section class="inner-hero"><div class="site-shell inner-hero__grid"><div><span class="section-kicker">Науковий підхід</span><h1>Рішення, підкріплені <em>агрономією</em></h1><p>Пояснюємо, як генетика, агротехніка та контроль якості формують потенціал майбутнього врожаю.</p></div><div class="inner-hero__icon"><i class="fa-solid fa-atom"></i></div></div></section>
<section class="content-section"><div class="site-shell"><div class="science-intro"><span class="section-kicker">Базові принципи</span><h2>Дві культури — один системний підхід</h2><p>Виробництво гібридного насіння поєднує генетичний добір, ізоляцію, контроль запилення та щадну післязбиральну обробку.</p></div><div class="article-grid"><article class="science-card science-card--sun"><div class="science-card__head"><i class="fa-solid fa-sun"></i><div><span>Helianthus annuus L.</span><h3>Соняшник</h3></div></div><ul><li><strong>Ізоляція.</strong> Захист насінницької ділянки від стороннього пилку.</li><li><strong>Сівозміна.</strong> Повернення на поле не раніше ніж через 5–6 років.</li><li><strong>Живлення.</strong> Баланс азоту, фосфору, калію та бору.</li><li><strong>Збирання.</strong> Контроль вологості та мінімізація травмування насіння.</li></ul></article><article class="science-card science-card--corn"><div class="science-card__head"><i class="fa-solid fa-seedling"></i><div><span>Zea mays L.</span><h3>Кукурудза</h3></div></div><ul><li><strong>Батьківські форми.</strong> Добір самозапилених ліній за продуктивністю.</li><li><strong>Контроль запилення.</strong> Синхронізація цвітіння та контроль материнських рядків.</li><li><strong>Сушіння.</strong> Щадний температурний режим для збереження схожості.</li><li><strong>Калібрування.</strong> Фракції для точного та рівномірного висіву.</li></ul></article></div></div></section>
<section class="content-section content-section--soft"><div class="site-shell"><div class="section-heading section-heading--center"><span class="section-kicker">Лабораторний контроль</span><h2>Показники, які ми перевіряємо</h2></div><div class="lab-grid"><div><i class="fa-solid fa-leaf"></i><strong>Схожість</strong><span>здатність партії формувати повноцінні сходи</span></div><div><i class="fa-solid fa-bolt"></i><strong>Енергія</strong><span>швидкість і дружність проростання</span></div><div><i class="fa-solid fa-droplet"></i><strong>Вологість</strong><span>безпечні показники для зберігання</span></div><div><i class="fa-solid fa-fingerprint"></i><strong>Чистота</strong><span>сортова та фізична однорідність</span></div></div></div></section>
@include('blocks.contact-cta')
@endsection
